version: '3.8'

services:
  app:
    build: .
    container_name: finance-app
    restart: always
    ports:
      - "80:3000" # Mapeia a porta 80 (HTTP padrão) para a 3000 do app
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=suasenhaforte
      - DB_NAME=finance_db
      - DB_PORT=5432
      # A chave do Gemini será injetada via arquivo .env na VPS
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: finance-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: suasenhaforte
      POSTGRES_DB: finance_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Limita memória para não travar sua VPS de 1GB
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  pgdata: